spring:
  application:
    name: email-service

  mail:
    host: smtp.mail.ovh.net
    port: 465
    username: contact@gilmotech.be
    password: Gilmo=270188
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    debug: true

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

springdoc:
  swagger-ui:
    path: /api/docs

app:
  mail:
    rate-limit:
      enabled: false

  cors:
    allowed-origins:
      - http://localhost:4200
      - https://assurantis.be
      - https://assurantis.gilmotech.be
      - https://www.gilmotech.be

server:
  port: 8080

logging:
  level:
    com.gilmotech.emailservice: DEBUG
    org.springframework.mail: DEBUG
